### ISSUE TITLE
Jellyfin Update don't work

### ISSUE THREAD

**Issue by bjk201** [community-scripts/ProxmoxVE#8513]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Jellyfin

### 📂 What was the exact command used to execute the script?

update

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 📈 Which Proxmox version are you on?

8.3

### 📝 Provide a clear and concise description of the issue.

type update - verbose on

       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              

  ⏳   Updating Intel Dependencies
[ERROR] in line 258: exit code 0: while executing command $STD apt-get install -y jq &> /dev/null

### 🔄 Steps to reproduce the issue.

1. update
2. choose verbose on

### ❌ Paste the full error output (if available).

       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              

  ⏳   Updating Intel Dependencies
[ERROR] in line 258: exit code 0: while executing command $STD apt-get install -y jq &> /dev/null

**Comment by MickLesk** [comment]
Thats your system

Run apt install jq inside LXC, does this Work?

**Comment by Zodsmar** [comment]
I also can't get it to work, but my error is more involved

```Reading package lists... Done: intel-igc-core-2 (2.18.5)
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 intel-igc-core-2 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.9 is installed
                    Depends: libstdc++6 (>= 13) but 12.3.0-1ubuntu1~22.04 is installed
                    Depends: libzstd1 (>= 1.5.5) but 1.4.8+dfsg-3build1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
(Reading database ... 29446 files and directories currently installed.)
Preparing to unpack .../intel-igc-core-2_2.18.5%2B19820_amd64.deb ...
Unpacking intel-igc-core-2 (2.18.5) over (2.18.5) ...
dpkg: dependency problems prevent configuration of intel-igc-core-2:
 intel-igc-core-2 depends on libc6 (>= 2.38); however:
  Version of libc6:amd64 on system is 2.35-0ubuntu3.9.
 intel-igc-core-2 depends on libstdc++6 (>= 13); however:
  Version of libstdc++6:amd64 on system is 12.3.0-1ubuntu1~22.04.
 intel-igc-core-2 depends on libzstd1 (>= 1.5.5); however:
  Version of libzstd1:amd64 on system is 1.4.8+dfsg-3build1.

dpkg: error processing package intel-igc-core-2 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 intel-igc-core-2
   ✖️   Both apt and dpkg installation failed

[ERROR] in line 32: exit code 0: while executing command return 1
```


Is this another Bookworm vs Trixie issue?

**Comment by MickLesk** [comment]
thats @CrazyWolf13 's feature, he take a look

**Comment by maxxie85** [comment]
I have the same issue output as @Zodsmar

**Comment by CrazyWolf13** [comment]
@Zodsmar @maxxie85 @bjk201 apologies, fix is up, and ready to be reviewed

**Comment by michelroegl-brunner** [comment]
Fix merged.

**Comment by CrazyWolf13** [comment]
For anyone with broken packages, running `apt --fix-broken install` then the update command again should fix it.

**Comment by maxxie85** [comment]
@CrazyWolf13 no apologies needed. That's why we have backups.

Update now went smooth. Thanks.

**Comment by Zodsmar** [comment]
Thanks for such a quick fix guys! Much appreciated <3

**Comment by Zodsmar** [comment]
> For anyone with broken packages, running `apt --fix-broken install` then the update command again should fix it.

@CrazyWolf13 
I actually am still having issues.

```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 intel-igc-core-2 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.9 is to be installed
                    Depends: libstdc++6 (>= 13) but 12.3.0-1ubuntu1~22.04 is to be installed
                    Depends: libzstd1 (>= 1.5.5) but 1.4.8+dfsg-3build1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

[ERROR] in line 42: exit code 0: while executing command $STD apt install -y libjemalloc2
```


Edit: You know I should probably not only read the comments above but actually process what is being said.... which I didn't do 

```apt --fix-broken install```first.... my bad. Its updating now! Thanks!

**Comment by Theetjuh** [comment]
I keep getting this issue ... I don't even have an Intel GPU

**Comment by CrazyWolf13** [comment]
@Theetjuh this is for iGPU so your integrated GPU inside your CPU.

Please post the full output from verbose update.

Have you tried the above steps with `apt --fix-broken install`

Do you run debian or ubuntu?

**Comment by Theetjuh** [comment]
I know, but I got an AMD processor, with their iGPU ;)
```
root@jellyfin:~# bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/jellyfin.sh)"
       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              

Reading package lists... Done: intel-igc-core-2 (2.20.3)
Building dependency tree... Done
Reading state information... Done
Note, selecting 'intel-igc-core-2' instead of '/tmp/tmp.Smru7cuqnK/intel-igc-core-2_2.20.3%2B19972_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 intel-igc-core-2 : Depends: libc6 (>= 2.38) but 2.36-9+deb12u13 is to be installed
                    Depends: libstdc++6 (>= 13) but 12.2.0-14+deb12u1 is to be installed
                    Depends: libzstd1 (>= 1.5.5) but 1.5.4+dfsg2-5 is to be installed
E: Unable to correct problems, you have held broken packages.
Selecting previously unselected package intel-igc-core-2.
(Reading database ... 24316 files and directories currently installed.)
Preparing to unpack .../intel-igc-core-2_2.20.3%2B19972_amd64.deb ...
Unpacking intel-igc-core-2 (2.20.3) ...
dpkg: dependency problems prevent configuration of intel-igc-core-2:
 intel-igc-core-2 depends on libc6 (>= 2.38); however:
  Version of libc6:amd64 on system is 2.36-9+deb12u13.
 intel-igc-core-2 depends on libstdc++6 (>= 13); however:
  Version of libstdc++6:amd64 on system is 12.2.0-14+deb12u1.
 intel-igc-core-2 depends on libzstd1 (>= 1.5.5); however:
  Version of libzstd1:amd64 on system is 1.5.4+dfsg2-5.

dpkg: error processing package intel-igc-core-2 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 intel-igc-core-2
   ✖️   Both apt and dpkg installation failed

[ERROR] in line 34: exit code 0: while executing command return 1
```
I ran the command, it fixed the issue and after running the update script again it got installed, with failed dependencies.
I am running Debian 12

**Comment by MickLesk** [comment]
You need to upgrade to trixie, libc6 is outdated in bookworm 

And If the issue come again -> new issue please

**Comment by Theetjuh** [comment]
> You need to upgrade to trixie, libc6 is outdated in bookworm
> 
> And If the issue come again -> new issue please

So the dependency is suddenly changed?
I have been running on Debian 12 for the past 2 years or so with this installation

Do I need to do this for all my LXC's?

**Comment by MickLesk** [comment]
Only when libc6 affected, so maybe all streaming LXC, Like jellyfin, emby and co. They are optimized for ubuntu

**Comment by CrazyWolf13** [comment]
@Theetjuh Yep that's most likely the issue here, look here on a bit older discussion on how to update to deb13, it's rather simple.

https://github.com/community-scripts/ProxmoxVE/discussions/7489

**Comment by Theetjuh** [comment]
> [@Theetjuh](https://github.com/Theetjuh) Yep that's most likely the issue here, look here on a bit older discussion on how to update to deb13, it's rather simple.
> 
> [#7489](https://github.com/community-scripts/ProxmoxVE/discussions/7489)

Thanks, the upgrade went smooth and the script works again
